### ISSUE TITLE
Can support pjax?

### ISSUE THREAD

**Issue by mrgeneralgoo** [next-theme/hexo-next-giscus#2]
```yaml
 # Easily enable fast Ajax navigation on your website.
 # For more information: https://github.com/next-theme/pjax
- pjax: true
+ pjax: false
```

**Comment by rocona** [comment]
暂时不支持，等我有空看下pjax，谢谢

**Comment by wasi-master** [comment]
It would be nice to have
本来很好

**Comment by Longhao-Chen** [comment]
启用 pjax 后，这个插件就失效了，要刷新，真心希望能够支持 pjax

不过 giscus 目前用的这种加载方式好像很难改成支持 pjax

**Comment by stevenjoezhang** [comment]
谢谢反馈，现在应该支持了 https://github.com/next-theme/hexo-next-giscus/commit/84531743bf8d86e12bb6f7950e81a5a135bc48c8

**Comment by mrgeneralgoo** [comment]
Nice!

Could you release a new version? @rocona @stevenjoezhang

**Comment by stevenjoezhang** [comment]
New version released: https://github.com/next-theme/hexo-next-giscus/releases/tag/1.1.0

**Comment by Longhao-Chen** [comment]
npmjs上也更新一下吧，目前好像还是1.0.3版本

**Comment by stevenjoezhang** [comment]
现在更新了，可以安装新版试试： https://www.npmjs.com/package/hexo-next-giscus/v/1.1.0
