### ISSUE TITLE
The comment box is unalligned - 评论框未对齐

### ISSUE THREAD

**Issue by wasi-master** [next-theme/hexo-next-giscus#3]
The comment box is a bit too far to the right
评论框有点偏右

![image](https://user-images.githubusercontent.com/63045920/148113672-9975158a-9e33-445c-b7f9-3b8af5eadcf1.png)

**Comment by rocona** [comment]
请更新到1.0.2版本

**Comment by wasi-master** [comment]
Thanks
谢谢
