### ISSUE TITLE
无法显示评论列表

### ISSUE THREAD

**Issue by yunnysunny** [next-theme/hexo-next-giscus#4]
我的博客链接 https://blog.whyun.com/posts/the-defect-of-node/ 中，有评论存在，但是界面上显示的评论为空。从网络请求中可以看到有如下 ajax 请求，但是请求的 http 状态码为 404

https://giscus.app/api/discussions?repo=yunnysunny%2Fyunnysunny.github.io&term=posts%2Fthe-defect-of-node%2F&category=Show+and+tell&number=0&last=15

**Comment by rocona** [comment]
看下 category 和 category id 是不是配置错了

**Comment by yunnysunny** [comment]
配置是对的

**Comment by rocona** [comment]
我看了下你的博客和github，category和category id是不匹配的
改成如下代码试一下
```
data-category="Show and tell"
data-category-id="DIC_kwDOATopus4B_4oh"
```

**Comment by yunnysunny** [comment]
果然是写错了，这个id只有最后一个字符不同，不细看还真发现不了
