### ISSUE TITLE
请问是否有办法检查哪一步出错了

### ISSUE THREAD

**Issue by Nicole-1996** [next-theme/hexo-next-giscus#9]
我按照网上的教程，先npm install hexo-next-giscus，然后运行结果是
<img width="487" alt="截屏2023-10-17 14 50 24" src="https://github.com/next-theme/hexo-next-giscus/assets/145549082/7081367b-c346-452b-8a81-ebbd781120f5">
然后在_config.yaml里面加入：
giscus:
  enable: true
  repo: Nicole-1996/blog_gitalk # Github repository name
  repo_id: R_kgDOKWcf2A # Github repository id
  category: Announcements # Github discussion category
  category_id: DIC_kwDOKWcf2M4CaJ82 # Github discussion category id
  mapping: pathname
  reactions_enabled: 1
  emit_metadata: 1
  theme: light
字段都是从giscus里复制的，运行了hexo clean; hexo g; hexo s，但是始终没法看到评论的框，应该如何检查哪里出了问题呢

**Comment by rocona** [comment]
在_config.next.yml配置

**Comment by stevenjoezhang** [comment]
最新版用 `_config.yml` 和 `_config.next.yml` 配置都是可以的，我测试了你的配置，也可以加载出评论框

**Comment by hilariouhiss** [comment]
我在_config.yml和_config.next.yml按官网和教程配置了giscus，clean后hexo g每次都渲染错误，Template render error: (D:\hexo\blog\themes\next\layout\category.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\category.swig) [Line 30, Column 53]
  Template render error: (D:\hexo\blog\themes\next\layout\category.swig) [Line 36, Column 23]
  Template render error: (D:\hexo\blog\themes\next\layout\category.swig) [Line 54, Column 17]
  Template render error: (D:\hexo\blog\themes\next\layout\category.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\_partials\head\head-unique.swig) [Line 10, Column 23]
  Template render error: (D:\hexo\blog\themes\next\layout\category.swig) [Line 4, Column 22]
  Template render error: (D:\hexo\blog\themes\next\layout\category.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\_partials\header\index.swig) [Line 6, Column 15]
  Template render error: (D:\hexo\blog\themes\next\layout\category.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\_partials\header\sub-menu.swig) [Line 2, Column 29]
  Template render error: (D:\hexo\blog\themes\next\layout\category.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\_partials\header\sub-menu.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\category.swig) [Line 6, Column 3]
  Template render error: (D:\hexo\blog\themes\next\layout\category.swig) [Line 22, Column 29]
  Template render error: (D:\hexo\blog\themes\next\layout\category.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\_partials\pagination.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\category.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\_partials\comments.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\category.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\_partials\languages.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\category.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\_third-party\math\index.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\category.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\_third-party\quicklink.swig)
  Template render error: (D:\hexo\blog\themes\next\layout\inject\bodyEnd\giscus.swig)
  Error: Unable to call `next_data`, which is undefined or falsey
    at Object._prettifyError (D:\hexo\blog\node_modules\nunjucks\src\lib.js:32:11)
    at D:\hexo\blog\node_modules\nunjucks\src\environment.js:464:19
    at Template.root [as rootRenderFunc] (eval at _compile (D:\hexo\blog\node_modules\nunjucks\src\environment.js:527:18), <anonymous>:51:3)
    at Template.render (D:\hexo\blog\node_modules\nunjucks\src\environment.js:454:10)
    at D:\hexo\blog\themes\next\scripts\renderer.js:32:29
    at _View._compiled (D:\hexo\blog\node_modules\hexo\dist\theme\view.js:120:67)
    at _View.render (D:\hexo\blog\node_modules\hexo\dist\theme\view.js:37:21)
    at D:\hexo\blog\node_modules\hexo\dist\hexo\index.js:60:29
    at tryCatcher (D:\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\hexo\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\hexo\blog\node_modules\hexo\dist\hexo\router.js:43:9)
    at Readable.read (node:internal/streams/readable:739:12)
    at resume_ (node:internal/streams/readable:1257:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)

**Comment by stevenjoezhang** [comment]
@hilariouhiss 你用的可能还是旧版的 NexT 主题，请尝试删除后重新安装，仓库链接为 https://github.com/next-theme/hexo-theme-next
